shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

# zsh-defer
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.compinit]
inline = "autoload -Uz compinit && zsh-defer compinit"

# zsh-syntax-highlighting
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply=["defer"]

# zsh-abbr
[plugins.zsh-abbr]
github = "olets/zsh-abbr"
apply=["defer"]

# zsh/sync配下のファイルは同期読み込みにする
[plugins.local-sync]
local = "~/.config/zsh/sync"
use = ["*.zsh"]

# zsh配下のファイルは遅延読み込みにする
[plugins.local-defer]
local = "~/.config/zsh"
use = ["*.zsh"]
apply=["defer"]

