return {
  "pwntester/octo.nvim",
  event = "VeryLazy",
  dependencies = {
    "nvim-lua/plenary.nvim",
    "nvim-telescope/telescope.nvim",
  },
  config = function()
    require("octo").setup({
      mappings_disable_default = false,
      mappings = {
        pull_request = {
          show_pr_diff = { lhs = "<localleader>d", desc = "show PR diff" },
          merge_pr = { lhs = "<localleader>mm", desc = "merge commit PR" },
          add_reviewer = { lhs = "<localleader>ra", desc = "add reviewer" },
          remove_reviewer = { lhs = "<localleader>rd", desc = "remove reviewer request" },
          reload = { lhs = "<C-r>", desc = "reload PR" },
          open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
          copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
          add_assignee = { lhs = "<localleader>aa", desc = "add assignee" },
          remove_assignee = { lhs = "<localleader>ad", desc = "remove assignee" },
          create_label = { lhs = "<localleader>lc", desc = "create label" },
          add_label = { lhs = "<localleader>la", desc = "add label" },
          remove_label = { lhs = "<localleader>ld", desc = "remove label" },
          add_comment = { lhs = "<localleader>ca", desc = "add comment" },
          delete_comment = { lhs = "<localleader>cd", desc = "delete comment" },
          next_comment = { lhs = "<localleader>cn", desc = "go to next comment" },
          prev_comment = { lhs = "<localleader>cp", desc = "go to previous comment" },
          react_hooray = { lhs = "<localleader>Rp", desc = "add/remove 🎉 reaction" },
          react_heart = { lhs = "<localleader>Rh", desc = "add/remove ❤️ reaction" },
          react_eyes = { lhs = "<localleader>Re", desc = "add/remove 👀 reaction" },
          react_thumbs_up = { lhs = "<localleader>R+", desc = "add/remove 👍 reaction" },
          react_thumbs_down = { lhs = "<localleader>R-", desc = "add/remove 👎 reaction" },
          react_rocket = { lhs = "<localleader>Rr", desc = "add/remove 🚀 reaction" },
          react_laugh = { lhs = "<localleader>Rl", desc = "add/remove 😄 reaction" },
          react_confused = { lhs = "<localleader>Rc", desc = "add/remove 😕 reaction" },
          review_start = { lhs = "<localleader>RS", desc = "start a review for the current PR" },
          review_resume = { lhs = "<localleader>RR", desc = "resume a pending review for the current PR" },
          list_commits = { lhs = "<localleader>Lc", desc = "list PR commits" },
          list_changed_files = { lhs = "<localleader>Lf", desc = "list PR changed files" },
          squash_and_merge_pr = { lhs = "<localleader>ms", desc = "squash and merge PR" },
          rebase_and_merge_pr = { lhs = "<localleader>mr", desc = "rebase and merge PR" },
        },
        review_thread = {
          goto_issue = { lhs = "<localleader>gi", desc = "navigate to a local repo issue" },
          add_comment = { lhs = "<localleader>ca", desc = "add comment" },
          add_suggestion = { lhs = "<localleader>sa", desc = "add suggestion" },
          delete_comment = { lhs = "<localleader>cd", desc = "delete comment" },
          next_comment = { lhs = "<localleader>cn", desc = "go to next comment" },
          prev_comment = { lhs = "<localleader>cp", desc = "go to previous comment" },
          select_next_entry = { lhs = "<localleader>fn", desc = "move to next changed file" },
          select_prev_entry = { lhs = "<localleader>fp", desc = "move to previous changed file" },
          select_first_entry = { lhs = "<localleader>ff", desc = "move to first changed file" },
          select_last_entry = { lhs = "<localleader>fl", desc = "move to last changed file" },
          close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
          react_hooray = { lhs = "<localleader>Rp", desc = "add/remove 🎉 reaction" },
          react_heart = { lhs = "<localleader>Rh", desc = "add/remove ❤️ reaction" },
          react_eyes = { lhs = "<localleader>Re", desc = "add/remove 👀 reaction" },
          react_thumbs_up = { lhs = "<localleader>R+", desc = "add/remove 👍 reaction" },
          react_thumbs_down = { lhs = "<localleader>R-", desc = "add/remove 👎 reaction" },
          react_rocket = { lhs = "<localleader>Rr", desc = "add/remove 🚀 reaction" },
          react_laugh = { lhs = "<localleader>Rl", desc = "add/remove 😄 reaction" },
          react_confused = { lhs = "<localleader>Rc", desc = "add/remove 😕 reaction" },
        },
        issue = {
          close_issue = { lhs = "<localleader>ic", desc = "close issue" },
          reopen_issue = { lhs = "<localleader>io", desc = "reopen issue" },
          list_issues = { lhs = "<localleader>Li", desc = "list open issues on same repo" },
          reload = { lhs = "<C-r>", desc = "reload issue" },
          open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
          copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
          add_assignee = { lhs = "<localleader>aa", desc = "add assignee" },
          remove_assignee = { lhs = "<localleader>ad", desc = "remove assignee" },
          create_label = { lhs = "<localleader>lc", desc = "create label" },
          add_label = { lhs = "<localleader>la", desc = "add label" },
          remove_label = { lhs = "<localleader>ld", desc = "remove label" },
          goto_issue = { lhs = "<localleader>ig", desc = "navigate to a local repo issue" },
          add_comment = { lhs = "<localleader>ca", desc = "add comment" },
          delete_comment = { lhs = "<localleader>cd", desc = "delete comment" },
          next_comment = { lhs = "<localleader>cn", desc = "go to next comment" },
          prev_comment = { lhs = "<localleader>cp", desc = "go to previous comment" },
          react_hooray = { lhs = "<localleader>Rp", desc = "add/remove 🎉 reaction" },
          react_heart = { lhs = "<localleader>Rh", desc = "add/remove ❤️ reaction" },
          react_eyes = { lhs = "<localleader>Re", desc = "add/remove 👀 reaction" },
          react_thumbs_up = { lhs = "<localleader>R+", desc = "add/remove 👍 reaction" },
          react_thumbs_down = { lhs = "<localleader>R-", desc = "add/remove 👎 reaction" },
          react_rocket = { lhs = "<localleader>Rr", desc = "add/remove 🚀 reaction" },
          react_laugh = { lhs = "<localleader>Rl", desc = "add/remove 😄 reaction" },
          react_confused = { lhs = "<localleader>Rc", desc = "add/remove 😕 reaction" },
        },
        submit_win = {
          approve_review = { lhs = "<C-a>", desc = "approve review" },
          comment_review = { lhs = "<C-m>", desc = "comment review" },
          request_changes = { lhs = "<C-r>", desc = "request changes review" },
          close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
        },
        review_diff = {
          submit_review = { lhs = "<localleader>vs", desc = "submit review" },
          discard_review = { lhs = "<localleader>vd", desc = "discard review" },
          add_review_comment = { lhs = "<localleader>ca", desc = "add a new review comment" },
          add_review_suggestion = { lhs = "<localleader>sa", desc = "add a new review suggestion" },
          focus_files = { lhs = "<localleader>ff", desc = "move focus to changed file panel" },
          toggle_files = { lhs = "<localleader>tf", desc = "hide/show changed files panel" },
          next_thread = { lhs = "<localleader>tn", desc = "move to next thread" },
          prev_thread = { lhs = "<localleader>tp", desc = "move to previous thread" },
          select_next_entry = { lhs = "<localleader>fn", desc = "move to next changed file" },
          select_prev_entry = { lhs = "<localleader>fp", desc = "move to previous changed file" },
          select_first_entry = { lhs = "<localleader>ff", desc = "move to first changed file" },
          select_last_entry = { lhs = "<localleader>fl", desc = "move to last changed file" },
          close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
          toggle_viewed = { lhs = "<localleader><space>", desc = "toggle viewer viewed state" },
          goto_file = { lhs = "<localleader>fg", desc = "go to file" },
        },
        file_panel = {
          submit_review = { lhs = "<localleader>vs", desc = "submit review" },
          discard_review = { lhs = "<localleader>vd", desc = "discard review" },
          next_entry = { lhs = "j", desc = "move to next changed file" },
          prev_entry = { lhs = "k", desc = "move to previous changed file" },
          select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
          refresh_files = { lhs = "R", desc = "refresh changed files panel" },
          focus_files = { lhs = "<localleader>ff", desc = "move focus to changed file panel" },
          toggle_files = { lhs = "<localleader>tf", desc = "hide/show changed files panel" },
          select_next_entry = { lhs = "<localleader>fn", desc = "move to next changed file" },
          select_prev_entry = { lhs = "<localleader>fp", desc = "move to previous changed file" },
          select_first_entry = { lhs = "<localleader>ff", desc = "move to first changed file" },
          select_last_entry = { lhs = "<localleader>fl", desc = "move to last changed file" },
          close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
          toggle_viewed = { lhs = "<localleader><space>", desc = "toggle viewer viewed state" },
        },
      },
    })

    local keymap = vim.keymap

    keymap.set("n", "<leader>opl", "<cmd>Octo pr list<CR>", { desc = "List PR" })
    keymap.set("n", "<leader>opc", "<cmd>Octo pr create<CR>", { desc = "Create PR" })
    keymap.set("n", "<leader>ops", "<cmd>Octo pr search<CR>", { desc = "Search PR" })
    keymap.set("n", "<leader>oil", "<cmd>Octo issue list<CR>", { desc = "List Issue" })
    keymap.set("n", "<leader>oic", "<cmd>Octo issue create<CR>", { desc = "Create Issue" })
    keymap.set("n", "<leader>ois", "<cmd>Octo issue search<CR>", { desc = "Search Issue" })
  end,
}
