[manager]
append_keymap = [
  # Seeking
  { on = "<C-k>", run = "seek -5", desc = "Seek up 5 units in the preview" },
  { on = "<C-j>", run = "seek 5",  desc = "Seek down 5 units in the preview" },
]

[input]
prepend_keymap = [
  { on = "<ESC>", run = "close", desc = "Cansel input" },
]
